# This is a basic workflow to help you get started with Actions

name: Simple update btc rates
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  run:
    name: update hkdhistorical
    runs-on: ubuntu-latest
    steps:    
      - name: setup actions
        uses: actions/checkout@v3
      - name: setup node version
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: add and push
        run: |
          npm install 
          npm install axios@0.26.1 --save
          node updaterate.js
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push



